from setuptools import setup

setup(
    name='drone_classification',
    version='',
    packages=['', 'env.lib.python3.6.site-packages.pip', 'env.lib.python3.6.site-packages.pip._vendor',
              'env.lib.python3.6.site-packages.pip._vendor.idna', 'env.lib.python3.6.site-packages.pip._vendor.pytoml',
              'env.lib.python3.6.site-packages.pip._vendor.certifi',
              'env.lib.python3.6.site-packages.pip._vendor.chardet',
              'env.lib.python3.6.site-packages.pip._vendor.chardet.cli',
              'env.lib.python3.6.site-packages.pip._vendor.distlib',
              'env.lib.python3.6.site-packages.pip._vendor.distlib._backport',
              'env.lib.python3.6.site-packages.pip._vendor.msgpack',
              'env.lib.python3.6.site-packages.pip._vendor.urllib3',
              'env.lib.python3.6.site-packages.pip._vendor.urllib3.util',
              'env.lib.python3.6.site-packages.pip._vendor.urllib3.contrib',
              'env.lib.python3.6.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'env.lib.python3.6.site-packages.pip._vendor.urllib3.packages',
              'env.lib.python3.6.site-packages.pip._vendor.urllib3.packages.backports',
              'env.lib.python3.6.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'env.lib.python3.6.site-packages.pip._vendor.colorama',
              'env.lib.python3.6.site-packages.pip._vendor.html5lib',
              'env.lib.python3.6.site-packages.pip._vendor.html5lib._trie',
              'env.lib.python3.6.site-packages.pip._vendor.html5lib.filters',
              'env.lib.python3.6.site-packages.pip._vendor.html5lib.treewalkers',
              'env.lib.python3.6.site-packages.pip._vendor.html5lib.treeadapters',
              'env.lib.python3.6.site-packages.pip._vendor.html5lib.treebuilders',
              'env.lib.python3.6.site-packages.pip._vendor.lockfile',
              'env.lib.python3.6.site-packages.pip._vendor.progress',
              'env.lib.python3.6.site-packages.pip._vendor.requests',
              'env.lib.python3.6.site-packages.pip._vendor.packaging',
              'env.lib.python3.6.site-packages.pip._vendor.cachecontrol',
              'env.lib.python3.6.site-packages.pip._vendor.cachecontrol.caches',
              'env.lib.python3.6.site-packages.pip._vendor.webencodings',
              'env.lib.python3.6.site-packages.pip._vendor.pkg_resources',
              'env.lib.python3.6.site-packages.pip._internal', 'env.lib.python3.6.site-packages.pip._internal.req',
              'env.lib.python3.6.site-packages.pip._internal.vcs',
              'env.lib.python3.6.site-packages.pip._internal.utils',
              'env.lib.python3.6.site-packages.pip._internal.models',
              'env.lib.python3.6.site-packages.pip._internal.commands',
              'env.lib.python3.6.site-packages.pip._internal.operations', 'env.lib.python3.6.site-packages.h5py',
              'env.lib.python3.6.site-packages.h5py._hl', 'env.lib.python3.6.site-packages.h5py.tests',
              'env.lib.python3.6.site-packages.h5py.tests.hl', 'env.lib.python3.6.site-packages.h5py.tests.old',
              'env.lib.python3.6.site-packages.pytz', 'env.lib.python3.6.site-packages.numpy',
              'env.lib.python3.6.site-packages.numpy.ma', 'env.lib.python3.6.site-packages.numpy.ma.tests',
              'env.lib.python3.6.site-packages.numpy.doc', 'env.lib.python3.6.site-packages.numpy.fft',
              'env.lib.python3.6.site-packages.numpy.fft.tests', 'env.lib.python3.6.site-packages.numpy.lib',
              'env.lib.python3.6.site-packages.numpy.lib.tests', 'env.lib.python3.6.site-packages.numpy.core',
              'env.lib.python3.6.site-packages.numpy.core.tests', 'env.lib.python3.6.site-packages.numpy.f2py',
              'env.lib.python3.6.site-packages.numpy.f2py.tests', 'env.lib.python3.6.site-packages.numpy.tests',
              'env.lib.python3.6.site-packages.numpy.compat', 'env.lib.python3.6.site-packages.numpy.compat.tests',
              'env.lib.python3.6.site-packages.numpy.linalg', 'env.lib.python3.6.site-packages.numpy.linalg.tests',
              'env.lib.python3.6.site-packages.numpy.random', 'env.lib.python3.6.site-packages.numpy.random.tests',
              'env.lib.python3.6.site-packages.numpy.testing', 'env.lib.python3.6.site-packages.numpy.testing.tests',
              'env.lib.python3.6.site-packages.numpy.testing._private',
              'env.lib.python3.6.site-packages.numpy.distutils',
              'env.lib.python3.6.site-packages.numpy.distutils.tests',
              'env.lib.python3.6.site-packages.numpy.distutils.command',
              'env.lib.python3.6.site-packages.numpy.distutils.fcompiler',
              'env.lib.python3.6.site-packages.numpy.matrixlib',
              'env.lib.python3.6.site-packages.numpy.matrixlib.tests',
              'env.lib.python3.6.site-packages.numpy.polynomial',
              'env.lib.python3.6.site-packages.numpy.polynomial.tests', 'env.lib.python3.6.site-packages.scipy',
              'env.lib.python3.6.site-packages.scipy.io', 'env.lib.python3.6.site-packages.scipy.io.arff',
              'env.lib.python3.6.site-packages.scipy.io.arff.tests', 'env.lib.python3.6.site-packages.scipy.io.tests',
              'env.lib.python3.6.site-packages.scipy.io.matlab',
              'env.lib.python3.6.site-packages.scipy.io.matlab.tests',
              'env.lib.python3.6.site-packages.scipy.io.harwell_boeing',
              'env.lib.python3.6.site-packages.scipy.io.harwell_boeing.tests',
              'env.lib.python3.6.site-packages.scipy.odr', 'env.lib.python3.6.site-packages.scipy.odr.tests',
              'env.lib.python3.6.site-packages.scipy._lib', 'env.lib.python3.6.site-packages.scipy._lib.tests',
              'env.lib.python3.6.site-packages.scipy.misc', 'env.lib.python3.6.site-packages.scipy.misc.tests',
              'env.lib.python3.6.site-packages.scipy.stats', 'env.lib.python3.6.site-packages.scipy.stats.tests',
              'env.lib.python3.6.site-packages.scipy.linalg', 'env.lib.python3.6.site-packages.scipy.linalg.tests',
              'env.lib.python3.6.site-packages.scipy.signal', 'env.lib.python3.6.site-packages.scipy.signal.tests',
              'env.lib.python3.6.site-packages.scipy.signal.windows', 'env.lib.python3.6.site-packages.scipy.sparse',
              'env.lib.python3.6.site-packages.scipy.sparse.tests',
              'env.lib.python3.6.site-packages.scipy.sparse.linalg',
              'env.lib.python3.6.site-packages.scipy.sparse.linalg.eigen',
              'env.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.arpack',
              'env.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.arpack.tests',
              'env.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.lobpcg',
              'env.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.lobpcg.tests',
              'env.lib.python3.6.site-packages.scipy.sparse.linalg.tests',
              'env.lib.python3.6.site-packages.scipy.sparse.linalg.dsolve',
              'env.lib.python3.6.site-packages.scipy.sparse.linalg.dsolve.tests',
              'env.lib.python3.6.site-packages.scipy.sparse.linalg.isolve',
              'env.lib.python3.6.site-packages.scipy.sparse.linalg.isolve.tests',
              'env.lib.python3.6.site-packages.scipy.sparse.csgraph',
              'env.lib.python3.6.site-packages.scipy.sparse.csgraph.tests',
              'env.lib.python3.6.site-packages.scipy.cluster', 'env.lib.python3.6.site-packages.scipy.cluster.tests',
              'env.lib.python3.6.site-packages.scipy.fftpack', 'env.lib.python3.6.site-packages.scipy.fftpack.tests',
              'env.lib.python3.6.site-packages.scipy.ndimage', 'env.lib.python3.6.site-packages.scipy.ndimage.tests',
              'env.lib.python3.6.site-packages.scipy.spatial', 'env.lib.python3.6.site-packages.scipy.spatial.tests',
              'env.lib.python3.6.site-packages.scipy.special', 'env.lib.python3.6.site-packages.scipy.special.tests',
              'env.lib.python3.6.site-packages.scipy.special._precompute',
              'env.lib.python3.6.site-packages.scipy.optimize', 'env.lib.python3.6.site-packages.scipy.optimize._lsq',
              'env.lib.python3.6.site-packages.scipy.optimize.tests',
              'env.lib.python3.6.site-packages.scipy.optimize._trlib',
              'env.lib.python3.6.site-packages.scipy.optimize._trustregion_constr',
              'env.lib.python3.6.site-packages.scipy.optimize._trustregion_constr.tests',
              'env.lib.python3.6.site-packages.scipy.constants',
              'env.lib.python3.6.site-packages.scipy.constants.tests',
              'env.lib.python3.6.site-packages.scipy.integrate', 'env.lib.python3.6.site-packages.scipy.integrate._ivp',
              'env.lib.python3.6.site-packages.scipy.integrate.tests',
              'env.lib.python3.6.site-packages.scipy.interpolate',
              'env.lib.python3.6.site-packages.scipy.interpolate.tests',
              'env.lib.python3.6.site-packages.scipy._build_utils', 'env.lib.python3.6.site-packages.pandas',
              'env.lib.python3.6.site-packages.pandas.io', 'env.lib.python3.6.site-packages.pandas.io.sas',
              'env.lib.python3.6.site-packages.pandas.io.json', 'env.lib.python3.6.site-packages.pandas.io.formats',
              'env.lib.python3.6.site-packages.pandas.io.msgpack',
              'env.lib.python3.6.site-packages.pandas.io.clipboard', 'env.lib.python3.6.site-packages.pandas.api',
              'env.lib.python3.6.site-packages.pandas.api.types',
              'env.lib.python3.6.site-packages.pandas.api.extensions', 'env.lib.python3.6.site-packages.pandas.core',
              'env.lib.python3.6.site-packages.pandas.core.util', 'env.lib.python3.6.site-packages.pandas.core.tools',
              'env.lib.python3.6.site-packages.pandas.core.arrays',
              'env.lib.python3.6.site-packages.pandas.core.dtypes',
              'env.lib.python3.6.site-packages.pandas.core.sparse',
              'env.lib.python3.6.site-packages.pandas.core.groupby',
              'env.lib.python3.6.site-packages.pandas.core.indexes',
              'env.lib.python3.6.site-packages.pandas.core.reshape',
              'env.lib.python3.6.site-packages.pandas.core.computation', 'env.lib.python3.6.site-packages.pandas.util',
              'env.lib.python3.6.site-packages.pandas._libs', 'env.lib.python3.6.site-packages.pandas._libs.tslibs',
              'env.lib.python3.6.site-packages.pandas.tests', 'env.lib.python3.6.site-packages.pandas.tests.io',
              'env.lib.python3.6.site-packages.pandas.tests.io.sas',
              'env.lib.python3.6.site-packages.pandas.tests.io.json',
              'env.lib.python3.6.site-packages.pandas.tests.io.parser',
              'env.lib.python3.6.site-packages.pandas.tests.io.formats',
              'env.lib.python3.6.site-packages.pandas.tests.io.msgpack',
              'env.lib.python3.6.site-packages.pandas.tests.api', 'env.lib.python3.6.site-packages.pandas.tests.util',
              'env.lib.python3.6.site-packages.pandas.tests.frame',
              'env.lib.python3.6.site-packages.pandas.tests.tools',
              'env.lib.python3.6.site-packages.pandas.tests.dtypes',
              'env.lib.python3.6.site-packages.pandas.tests.scalar',
              'env.lib.python3.6.site-packages.pandas.tests.scalar.period',
              'env.lib.python3.6.site-packages.pandas.tests.scalar.interval',
              'env.lib.python3.6.site-packages.pandas.tests.scalar.timedelta',
              'env.lib.python3.6.site-packages.pandas.tests.scalar.timestamp',
              'env.lib.python3.6.site-packages.pandas.tests.series',
              'env.lib.python3.6.site-packages.pandas.tests.series.indexing',
              'env.lib.python3.6.site-packages.pandas.tests.sparse',
              'env.lib.python3.6.site-packages.pandas.tests.sparse.frame',
              'env.lib.python3.6.site-packages.pandas.tests.sparse.series',
              'env.lib.python3.6.site-packages.pandas.tests.tslibs',
              'env.lib.python3.6.site-packages.pandas.tests.generic',
              'env.lib.python3.6.site-packages.pandas.tests.groupby',
              'env.lib.python3.6.site-packages.pandas.tests.groupby.aggregate',
              'env.lib.python3.6.site-packages.pandas.tests.indexes',
              'env.lib.python3.6.site-packages.pandas.tests.indexes.period',
              'env.lib.python3.6.site-packages.pandas.tests.indexes.interval',
              'env.lib.python3.6.site-packages.pandas.tests.indexes.datetimes',
              'env.lib.python3.6.site-packages.pandas.tests.indexes.timedeltas',
              'env.lib.python3.6.site-packages.pandas.tests.reshape',
              'env.lib.python3.6.site-packages.pandas.tests.reshape.merge',
              'env.lib.python3.6.site-packages.pandas.tests.tseries',
              'env.lib.python3.6.site-packages.pandas.tests.tseries.offsets',
              'env.lib.python3.6.site-packages.pandas.tests.indexing',
              'env.lib.python3.6.site-packages.pandas.tests.indexing.interval',
              'env.lib.python3.6.site-packages.pandas.tests.plotting',
              'env.lib.python3.6.site-packages.pandas.tests.extension',
              'env.lib.python3.6.site-packages.pandas.tests.extension.base',
              'env.lib.python3.6.site-packages.pandas.tests.extension.json',
              'env.lib.python3.6.site-packages.pandas.tests.extension.decimal',
              'env.lib.python3.6.site-packages.pandas.tests.extension.category',
              'env.lib.python3.6.site-packages.pandas.tests.internals',
              'env.lib.python3.6.site-packages.pandas.tests.categorical',
              'env.lib.python3.6.site-packages.pandas.tests.computation',
              'env.lib.python3.6.site-packages.pandas.tools', 'env.lib.python3.6.site-packages.pandas.types',
              'env.lib.python3.6.site-packages.pandas.compat', 'env.lib.python3.6.site-packages.pandas.compat.numpy',
              'env.lib.python3.6.site-packages.pandas.errors', 'env.lib.python3.6.site-packages.pandas.formats',
              'env.lib.python3.6.site-packages.pandas.tseries', 'env.lib.python3.6.site-packages.pandas.plotting',
              'env.lib.python3.6.site-packages.pandas.computation', 'env.lib.python3.6.site-packages.fastdtw',
              'env.lib.python3.6.site-packages.seaborn', 'env.lib.python3.6.site-packages.seaborn.tests',
              'env.lib.python3.6.site-packages.seaborn.colors', 'env.lib.python3.6.site-packages.seaborn.external',
              'env.lib.python3.6.site-packages.dateutil', 'env.lib.python3.6.site-packages.dateutil.tz',
              'env.lib.python3.6.site-packages.dateutil.parser', 'env.lib.python3.6.site-packages.dateutil.zoneinfo',
              'env.lib.python3.6.site-packages.ruptures', 'env.lib.python3.6.site-packages.ruptures.show',
              'env.lib.python3.6.site-packages.ruptures.costs', 'env.lib.python3.6.site-packages.ruptures.utils',
              'env.lib.python3.6.site-packages.ruptures.metrics', 'env.lib.python3.6.site-packages.ruptures.datasets',
              'env.lib.python3.6.site-packages.ruptures.detection', 'env.lib.python3.6.site-packages.matplotlib',
              'env.lib.python3.6.site-packages.matplotlib.tri', 'env.lib.python3.6.site-packages.matplotlib.axes',
              'env.lib.python3.6.site-packages.matplotlib.cbook', 'env.lib.python3.6.site-packages.matplotlib.style',
              'env.lib.python3.6.site-packages.matplotlib.tests', 'env.lib.python3.6.site-packages.matplotlib.compat',
              'env.lib.python3.6.site-packages.matplotlib.testing',
              'env.lib.python3.6.site-packages.matplotlib.testing.jpl_units',
              'env.lib.python3.6.site-packages.matplotlib.backends',
              'env.lib.python3.6.site-packages.matplotlib.backends.qt_editor',
              'env.lib.python3.6.site-packages.matplotlib.sphinxext',
              'env.lib.python3.6.site-packages.matplotlib.sphinxext.tests',
              'env.lib.python3.6.site-packages.matplotlib.projections',
              'env.lib.python3.6.site-packages.mpl_toolkits.tests',
              'env.lib.python3.6.site-packages.mpl_toolkits.mplot3d',
              'env.lib.python3.6.site-packages.mpl_toolkits.axes_grid',
              'env.lib.python3.6.site-packages.mpl_toolkits.axes_grid1',
              'env.lib.python3.6.site-packages.mpl_toolkits.axisartist', 'venv.lib.python3.7.site-packages.pip',
              'venv.lib.python3.7.site-packages.pip._vendor', 'venv.lib.python3.7.site-packages.pip._vendor.idna',
              'venv.lib.python3.7.site-packages.pip._vendor.pytoml',
              'venv.lib.python3.7.site-packages.pip._vendor.certifi',
              'venv.lib.python3.7.site-packages.pip._vendor.chardet',
              'venv.lib.python3.7.site-packages.pip._vendor.chardet.cli',
              'venv.lib.python3.7.site-packages.pip._vendor.distlib',
              'venv.lib.python3.7.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python3.7.site-packages.pip._vendor.msgpack',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.util',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.packages',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.7.site-packages.pip._vendor.colorama',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.7.site-packages.pip._vendor.lockfile',
              'venv.lib.python3.7.site-packages.pip._vendor.progress',
              'venv.lib.python3.7.site-packages.pip._vendor.requests',
              'venv.lib.python3.7.site-packages.pip._vendor.packaging',
              'venv.lib.python3.7.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python3.7.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.7.site-packages.pip._vendor.webencodings',
              'venv.lib.python3.7.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.7.site-packages.pip._internal', 'venv.lib.python3.7.site-packages.pip._internal.req',
              'venv.lib.python3.7.site-packages.pip._internal.vcs',
              'venv.lib.python3.7.site-packages.pip._internal.utils',
              'venv.lib.python3.7.site-packages.pip._internal.models',
              'venv.lib.python3.7.site-packages.pip._internal.commands',
              'venv.lib.python3.7.site-packages.pip._internal.operations', 'venv.lib.python3.7.site-packages.h5py',
              'venv.lib.python3.7.site-packages.h5py._hl', 'venv.lib.python3.7.site-packages.h5py.tests',
              'venv.lib.python3.7.site-packages.h5py.tests.hl', 'venv.lib.python3.7.site-packages.h5py.tests.old',
              'venv.lib.python3.7.site-packages.pytz', 'venv.lib.python3.7.site-packages.numpy',
              'venv.lib.python3.7.site-packages.numpy.ma', 'venv.lib.python3.7.site-packages.numpy.ma.tests',
              'venv.lib.python3.7.site-packages.numpy.doc', 'venv.lib.python3.7.site-packages.numpy.fft',
              'venv.lib.python3.7.site-packages.numpy.fft.tests', 'venv.lib.python3.7.site-packages.numpy.lib',
              'venv.lib.python3.7.site-packages.numpy.lib.tests', 'venv.lib.python3.7.site-packages.numpy.core',
              'venv.lib.python3.7.site-packages.numpy.core.tests', 'venv.lib.python3.7.site-packages.numpy.f2py',
              'venv.lib.python3.7.site-packages.numpy.f2py.tests', 'venv.lib.python3.7.site-packages.numpy.tests',
              'venv.lib.python3.7.site-packages.numpy.compat', 'venv.lib.python3.7.site-packages.numpy.compat.tests',
              'venv.lib.python3.7.site-packages.numpy.linalg', 'venv.lib.python3.7.site-packages.numpy.linalg.tests',
              'venv.lib.python3.7.site-packages.numpy.random', 'venv.lib.python3.7.site-packages.numpy.random.tests',
              'venv.lib.python3.7.site-packages.numpy.testing', 'venv.lib.python3.7.site-packages.numpy.testing.tests',
              'venv.lib.python3.7.site-packages.numpy.testing._private',
              'venv.lib.python3.7.site-packages.numpy.distutils',
              'venv.lib.python3.7.site-packages.numpy.distutils.tests',
              'venv.lib.python3.7.site-packages.numpy.distutils.command',
              'venv.lib.python3.7.site-packages.numpy.distutils.fcompiler',
              'venv.lib.python3.7.site-packages.numpy.matrixlib',
              'venv.lib.python3.7.site-packages.numpy.matrixlib.tests',
              'venv.lib.python3.7.site-packages.numpy.polynomial',
              'venv.lib.python3.7.site-packages.numpy.polynomial.tests', 'venv.lib.python3.7.site-packages.scipy',
              'venv.lib.python3.7.site-packages.scipy.io', 'venv.lib.python3.7.site-packages.scipy.io.arff',
              'venv.lib.python3.7.site-packages.scipy.io.arff.tests', 'venv.lib.python3.7.site-packages.scipy.io.tests',
              'venv.lib.python3.7.site-packages.scipy.io.matlab',
              'venv.lib.python3.7.site-packages.scipy.io.matlab.tests',
              'venv.lib.python3.7.site-packages.scipy.io.harwell_boeing',
              'venv.lib.python3.7.site-packages.scipy.io.harwell_boeing.tests',
              'venv.lib.python3.7.site-packages.scipy.odr', 'venv.lib.python3.7.site-packages.scipy.odr.tests',
              'venv.lib.python3.7.site-packages.scipy._lib', 'venv.lib.python3.7.site-packages.scipy._lib.tests',
              'venv.lib.python3.7.site-packages.scipy.misc', 'venv.lib.python3.7.site-packages.scipy.misc.tests',
              'venv.lib.python3.7.site-packages.scipy.stats', 'venv.lib.python3.7.site-packages.scipy.stats.tests',
              'venv.lib.python3.7.site-packages.scipy.linalg', 'venv.lib.python3.7.site-packages.scipy.linalg.tests',
              'venv.lib.python3.7.site-packages.scipy.signal', 'venv.lib.python3.7.site-packages.scipy.signal.tests',
              'venv.lib.python3.7.site-packages.scipy.signal.windows', 'venv.lib.python3.7.site-packages.scipy.sparse',
              'venv.lib.python3.7.site-packages.scipy.sparse.tests',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.eigen',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.eigen.arpack',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.eigen.arpack.tests',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.eigen.lobpcg',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.eigen.lobpcg.tests',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.tests',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.dsolve',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.dsolve.tests',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.isolve',
              'venv.lib.python3.7.site-packages.scipy.sparse.linalg.isolve.tests',
              'venv.lib.python3.7.site-packages.scipy.sparse.csgraph',
              'venv.lib.python3.7.site-packages.scipy.sparse.csgraph.tests',
              'venv.lib.python3.7.site-packages.scipy.cluster', 'venv.lib.python3.7.site-packages.scipy.cluster.tests',
              'venv.lib.python3.7.site-packages.scipy.fftpack', 'venv.lib.python3.7.site-packages.scipy.fftpack.tests',
              'venv.lib.python3.7.site-packages.scipy.ndimage', 'venv.lib.python3.7.site-packages.scipy.ndimage.tests',
              'venv.lib.python3.7.site-packages.scipy.spatial', 'venv.lib.python3.7.site-packages.scipy.spatial.tests',
              'venv.lib.python3.7.site-packages.scipy.special', 'venv.lib.python3.7.site-packages.scipy.special.tests',
              'venv.lib.python3.7.site-packages.scipy.special._precompute',
              'venv.lib.python3.7.site-packages.scipy.optimize', 'venv.lib.python3.7.site-packages.scipy.optimize._lsq',
              'venv.lib.python3.7.site-packages.scipy.optimize.tests',
              'venv.lib.python3.7.site-packages.scipy.optimize._trlib',
              'venv.lib.python3.7.site-packages.scipy.optimize._trustregion_constr',
              'venv.lib.python3.7.site-packages.scipy.optimize._trustregion_constr.tests',
              'venv.lib.python3.7.site-packages.scipy.constants',
              'venv.lib.python3.7.site-packages.scipy.constants.tests',
              'venv.lib.python3.7.site-packages.scipy.integrate',
              'venv.lib.python3.7.site-packages.scipy.integrate._ivp',
              'venv.lib.python3.7.site-packages.scipy.integrate.tests',
              'venv.lib.python3.7.site-packages.scipy.interpolate',
              'venv.lib.python3.7.site-packages.scipy.interpolate.tests',
              'venv.lib.python3.7.site-packages.scipy._build_utils', 'venv.lib.python3.7.site-packages.pandas',
              'venv.lib.python3.7.site-packages.pandas.io', 'venv.lib.python3.7.site-packages.pandas.io.sas',
              'venv.lib.python3.7.site-packages.pandas.io.json', 'venv.lib.python3.7.site-packages.pandas.io.formats',
              'venv.lib.python3.7.site-packages.pandas.io.msgpack',
              'venv.lib.python3.7.site-packages.pandas.io.clipboard', 'venv.lib.python3.7.site-packages.pandas.api',
              'venv.lib.python3.7.site-packages.pandas.api.types',
              'venv.lib.python3.7.site-packages.pandas.api.extensions', 'venv.lib.python3.7.site-packages.pandas.core',
              'venv.lib.python3.7.site-packages.pandas.core.util', 'venv.lib.python3.7.site-packages.pandas.core.tools',
              'venv.lib.python3.7.site-packages.pandas.core.arrays',
              'venv.lib.python3.7.site-packages.pandas.core.dtypes',
              'venv.lib.python3.7.site-packages.pandas.core.sparse',
              'venv.lib.python3.7.site-packages.pandas.core.groupby',
              'venv.lib.python3.7.site-packages.pandas.core.indexes',
              'venv.lib.python3.7.site-packages.pandas.core.reshape',
              'venv.lib.python3.7.site-packages.pandas.core.computation',
              'venv.lib.python3.7.site-packages.pandas.util', 'venv.lib.python3.7.site-packages.pandas._libs',
              'venv.lib.python3.7.site-packages.pandas._libs.tslibs', 'venv.lib.python3.7.site-packages.pandas.tests',
              'venv.lib.python3.7.site-packages.pandas.tests.io',
              'venv.lib.python3.7.site-packages.pandas.tests.io.sas',
              'venv.lib.python3.7.site-packages.pandas.tests.io.json',
              'venv.lib.python3.7.site-packages.pandas.tests.io.parser',
              'venv.lib.python3.7.site-packages.pandas.tests.io.formats',
              'venv.lib.python3.7.site-packages.pandas.tests.io.msgpack',
              'venv.lib.python3.7.site-packages.pandas.tests.api', 'venv.lib.python3.7.site-packages.pandas.tests.util',
              'venv.lib.python3.7.site-packages.pandas.tests.frame',
              'venv.lib.python3.7.site-packages.pandas.tests.tools',
              'venv.lib.python3.7.site-packages.pandas.tests.dtypes',
              'venv.lib.python3.7.site-packages.pandas.tests.scalar',
              'venv.lib.python3.7.site-packages.pandas.tests.scalar.period',
              'venv.lib.python3.7.site-packages.pandas.tests.scalar.interval',
              'venv.lib.python3.7.site-packages.pandas.tests.scalar.timedelta',
              'venv.lib.python3.7.site-packages.pandas.tests.scalar.timestamp',
              'venv.lib.python3.7.site-packages.pandas.tests.series',
              'venv.lib.python3.7.site-packages.pandas.tests.series.indexing',
              'venv.lib.python3.7.site-packages.pandas.tests.sparse',
              'venv.lib.python3.7.site-packages.pandas.tests.sparse.frame',
              'venv.lib.python3.7.site-packages.pandas.tests.sparse.series',
              'venv.lib.python3.7.site-packages.pandas.tests.tslibs',
              'venv.lib.python3.7.site-packages.pandas.tests.generic',
              'venv.lib.python3.7.site-packages.pandas.tests.groupby',
              'venv.lib.python3.7.site-packages.pandas.tests.groupby.aggregate',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes.period',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes.interval',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes.datetimes',
              'venv.lib.python3.7.site-packages.pandas.tests.indexes.timedeltas',
              'venv.lib.python3.7.site-packages.pandas.tests.reshape',
              'venv.lib.python3.7.site-packages.pandas.tests.reshape.merge',
              'venv.lib.python3.7.site-packages.pandas.tests.tseries',
              'venv.lib.python3.7.site-packages.pandas.tests.tseries.offsets',
              'venv.lib.python3.7.site-packages.pandas.tests.indexing',
              'venv.lib.python3.7.site-packages.pandas.tests.indexing.interval',
              'venv.lib.python3.7.site-packages.pandas.tests.plotting',
              'venv.lib.python3.7.site-packages.pandas.tests.extension',
              'venv.lib.python3.7.site-packages.pandas.tests.extension.base',
              'venv.lib.python3.7.site-packages.pandas.tests.extension.json',
              'venv.lib.python3.7.site-packages.pandas.tests.extension.decimal',
              'venv.lib.python3.7.site-packages.pandas.tests.extension.category',
              'venv.lib.python3.7.site-packages.pandas.tests.internals',
              'venv.lib.python3.7.site-packages.pandas.tests.categorical',
              'venv.lib.python3.7.site-packages.pandas.tests.computation',
              'venv.lib.python3.7.site-packages.pandas.tools', 'venv.lib.python3.7.site-packages.pandas.types',
              'venv.lib.python3.7.site-packages.pandas.compat', 'venv.lib.python3.7.site-packages.pandas.compat.numpy',
              'venv.lib.python3.7.site-packages.pandas.errors', 'venv.lib.python3.7.site-packages.pandas.formats',
              'venv.lib.python3.7.site-packages.pandas.tseries', 'venv.lib.python3.7.site-packages.pandas.plotting',
              'venv.lib.python3.7.site-packages.pandas.computation', 'venv.lib.python3.7.site-packages.fastdtw',
              'venv.lib.python3.7.site-packages.seaborn', 'venv.lib.python3.7.site-packages.seaborn.tests',
              'venv.lib.python3.7.site-packages.seaborn.colors', 'venv.lib.python3.7.site-packages.seaborn.external',
              'venv.lib.python3.7.site-packages.dateutil', 'venv.lib.python3.7.site-packages.dateutil.tz',
              'venv.lib.python3.7.site-packages.dateutil.parser', 'venv.lib.python3.7.site-packages.dateutil.zoneinfo',
              'venv.lib.python3.7.site-packages.ruptures', 'venv.lib.python3.7.site-packages.ruptures.show',
              'venv.lib.python3.7.site-packages.ruptures.costs', 'venv.lib.python3.7.site-packages.ruptures.utils',
              'venv.lib.python3.7.site-packages.ruptures.metrics', 'venv.lib.python3.7.site-packages.ruptures.datasets',
              'venv.lib.python3.7.site-packages.ruptures.detection', 'venv.lib.python3.7.site-packages.matplotlib',
              'venv.lib.python3.7.site-packages.matplotlib.tri', 'venv.lib.python3.7.site-packages.matplotlib.axes',
              'venv.lib.python3.7.site-packages.matplotlib.cbook', 'venv.lib.python3.7.site-packages.matplotlib.style',
              'venv.lib.python3.7.site-packages.matplotlib.tests', 'venv.lib.python3.7.site-packages.matplotlib.compat',
              'venv.lib.python3.7.site-packages.matplotlib.testing',
              'venv.lib.python3.7.site-packages.matplotlib.testing.jpl_units',
              'venv.lib.python3.7.site-packages.matplotlib.backends',
              'venv.lib.python3.7.site-packages.matplotlib.backends.qt_editor',
              'venv.lib.python3.7.site-packages.matplotlib.sphinxext',
              'venv.lib.python3.7.site-packages.matplotlib.sphinxext.tests',
              'venv.lib.python3.7.site-packages.matplotlib.projections',
              'venv.lib.python3.7.site-packages.mpl_toolkits.tests',
              'venv.lib.python3.7.site-packages.mpl_toolkits.mplot3d',
              'venv.lib.python3.7.site-packages.mpl_toolkits.axes_grid',
              'venv.lib.python3.7.site-packages.mpl_toolkits.axes_grid1',
              'venv.lib.python3.7.site-packages.mpl_toolkits.axisartist', 'tests', 'drone_classification',
              'drone_classification.math'],
    url='',
    license='',
    author='gavinaboulhosn',
    author_email='gnaboulh@ncsu.edu',
    description=''
)
