from drone_classification.math.CPD import changepoint_detection
from drone_classification.get_data_path import get_data_path
from drone_classification.matio import matio
import matplotlib.pyplot as plt